image: docker:latest

services:
- docker:dind

before_script:
- ip a s
- apk add --update bash make sed
- docker version
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"



build-all:
  stage: build
  script:
    - make
  artifacts:
    paths:
    - gromacs/gmx-docker
  only:
    - master
