image: docker:latest

services:
- docker:dind

before_script:
- ip a s
- apk add --update bash
- docker version
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"



build-all:
  stage: build
  script:
    - ls -l
    - bash ./build-all.sh
  only:
    - master
