#!/bin/bash

WORKDIR="$PWD"

if [ -z "$GMX_DOUBLE" ]; then
	GMX_DOUBLE=OFF
	b=$(basename $0) 
	[ $b = gmx_d -o $b = mdrun_d ] && GMX_DOUBLE=ON
	export GMX_DOUBLE
fi

source /gromacs/gmx-chooser.sh

if [ $(basename $0 _d) = mdrun ]; then
	gmx mdrun "$@"
else
	gmx "$@"
fi 

